services:
  - type: web
    name: bookverse-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BOOKVERSE_OWNER_EMAIL
        sync: false
      - key: CORS_ORIGINS
        value: https://bookverse-landing.onrender.com,https://bookverse-buyer.onrender.com,https://bookverse-seller.onrender.com,https://localhost

  - type: web
    runtime: static
    name: bookverse-landing
    rootDir: frontend/landing
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SELLER_PORTAL_URL
        value: https://bookverse-seller.onrender.com
      - key: VITE_BUYER_PORTAL_URL
        value: https://bookverse-buyer.onrender.com

  - type: web
    runtime: static
    name: bookverse-seller
    rootDir: frontend/seller-portal
    buildFilter:
      paths:
        - frontend/seller-portal/**
        - frontend/shared/**
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://bookverse-api-uoc8.onrender.com/api/v1
      - key: VITE_LANDING_URL
        value: https://bookverse-landing.onrender.com

  - type: web
    runtime: static
    name: bookverse-buyer
    rootDir: frontend/buyer-portal
    buildFilter:
      paths:
        - frontend/buyer-portal/**
        - frontend/shared/**
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://bookverse-api-uoc8.onrender.com/api/v1
      - key: VITE_LANDING_URL
        value: https://bookverse-landing.onrender.com
